const data1 = {
  request_info: {
    success: true,
    credits_used: 3,
    credits_remaining: 97,
    credits_used_this_request: 1,
  },
  request_metadata: {
    created_at: "2021-11-28T17:29:12.758Z",
    processed_at: "2021-11-28T17:29:18.449Z",
    total_time_taken: 5.69,
    amazon_url:
      "https://www.amazon.in/s/?k=photo+frames&ref=nb_sb_noss_2&s=relevanceblender&language=en_US",
  },
  request_parameters: {
    type: "search",
    amazon_domain: "amazon.in",
    search_term: "photo frames",
    output: "json",
    language: "en_US",
    sort_by: "featured",
  },
  search_results: [
    {
      position: 1,
      title:
        "Amazon Brand - Solimo Collage Photo Frames (Set of 11, Wall Hanging),Black (SOL-HD-PF2)",
      asin: "B076VF43H3",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_aps_sr_pg1_1?ie=UTF8&adId=A0180345YYWZAFJSR30S&url=%2FAmazon-Brand-Solimo-Collage-Hanging%2Fdp%2FB076VF43H3%2Fref%3Dsr_1_1_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26sr%3D8-1-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_atf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71mqJyckdsL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.1,
      ratings_total: 448,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 851,
          currency: "INR",
          raw: "₹851",
          name: "₹851₹851 ₹2,500₹2,500",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 2500,
          currency: "INR",
          raw: "₹2,500",
          name: "₹851₹851 ₹2,500₹2,500",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 851,
        currency: "INR",
        raw: "₹851",
        name: "₹851₹851 ₹2,500₹2,500",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 2,
      title: 'AmazonBasics Photo Frame with Stand, Set of 5 | 8" x 10", Black',
      asin: "B079LC6XCD",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_aps_sr_pg1_1?ie=UTF8&adId=A0102661BW8ACCDB2O1Z&url=%2FAmazonBasics-Table-Photo-Frames-Stand%2Fdp%2FB079LC6XCD%2Fref%3Dsr_1_2_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26sr%3D8-2-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_atf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71vD1klNDbL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.6,
      ratings_total: 876,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 1829,
          currency: "INR",
          raw: "₹1,829",
          name: "₹1,829₹1,829 ₹3,000₹3,000",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 3000,
          currency: "INR",
          raw: "₹3,000",
          name: "₹1,829₹1,829 ₹3,000₹3,000",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1829,
        currency: "INR",
        raw: "₹1,829",
        name: "₹1,829₹1,829 ₹3,000₹3,000",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 3,
      title:
        "KDM Home Decor 1 Pcs 10x12 Inch Golden Bindi Color Flexible Glass & Synthetic Wood Hanging/Table Top Modern Photo Frame for Wall Decoration",
      asin: "B09LSK58VW",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_aps_sr_pg1_1?ie=UTF8&adId=A06997602OACDI4PE26L8&url=%2FKDM-Home-Decor-Synthetic-Decoration%2Fdp%2FB09LSK58VW%2Fref%3Dsr_1_3_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26sr%3D8-3-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_atf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61sy9v0stgS._AC_UL320_.jpg",
      coupon: {
        badge_text: "Save ₹20",
        text: "with coupon",
      },
      is_prime: true,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 499,
          currency: "INR",
          raw: "₹499",
          name: "Primary",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1764,
          currency: "INR",
          raw: "₹1,764",
          name: "Original",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 499,
        currency: "INR",
        raw: "₹499",
        name: "Primary",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Saturday, December 4",
      },
    },
    {
      position: 4,
      title:
        "KDM Home Decor 1 Pcs 5x7 Inches Flexible Glass & Synthetic Wood Hanging/Table Top Modern Art Photo Frame for Wall Decoration Chatai Brown Color",
      asin: "B09LSLXB4F",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_aps_sr_pg1_1?ie=UTF8&adId=A09310881WUBYO644968X&url=%2FKDM-Home-Decor-Synthetic-Decoration%2Fdp%2FB09LSLXB4F%2Fref%3Dsr_1_4_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26sr%3D8-4-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_atf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/616s7+H8nsS._AC_UL320_.jpg",
      coupon: {
        badge_text: "Save ₹20",
        text: "with coupon",
      },
      is_prime: true,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 378,
          currency: "INR",
          raw: "₹378",
          name: "Primary",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1134,
          currency: "INR",
          raw: "₹1,134",
          name: "Original",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 378,
        currency: "INR",
        raw: "₹378",
        name: "Primary",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Saturday, December 4",
      },
    },
    {
      position: 5,
      title:
        "Art Street Shooting Star Photo Frame Set of 16 Individual Photo Frames with Hanging Accessories (3 Units of 8x10, 4 Units of 6x8, 4 Units of 5x7, 3 Units of 4x6, 2 Units of 6x10)",
      asin: "B0753L1QSM",
      link: "https://www.amazon.in/Painting-Mantra-Individual-Photo-Frame/dp/B0753L1QSM/ref=sr_1_5?keywords=photo+frames&qid=1638120555&sr=8-5",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/719hT771ehL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.1,
      ratings_total: 4593,
      prices: [
        {
          symbol: "₹",
          value: 1549,
          currency: "INR",
          raw: "₹1,549",
          name: "₹1,549₹1,549 ₹3,000₹3,000",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 3000,
          currency: "INR",
          raw: "₹3,000",
          name: "₹1,549₹1,549 ₹3,000₹3,000",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1549,
        currency: "INR",
        raw: "₹1,549",
        name: "₹1,549₹1,549 ₹3,000₹3,000",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 6,
      title:
        "Painting Mantra Art Street Boulevard Photo Frame Set of 11 Picture Frames for Wall Hanging (8x10-3 pcs, 6x8-8 pcs)-Black and White, synthetic wood",
      asin: "B076SGJRKQ",
      link: "https://www.amazon.in/Painting-Mantra-Boulevard-Polymer-Photo/dp/B076SGJRKQ/ref=sr_1_6?keywords=photo+frames&qid=1638120555&sr=8-6",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71LuwKCsyUL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.2,
      ratings_total: 2101,
      prices: [
        {
          symbol: "₹",
          value: 1149,
          currency: "INR",
          raw: "₹1,149",
          name: "₹1,149₹1,149 ₹1,399₹1,399",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1399,
          currency: "INR",
          raw: "₹1,399",
          name: "₹1,149₹1,149 ₹1,399₹1,399",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1149,
        currency: "INR",
        raw: "₹1,149",
        name: "₹1,149₹1,149 ₹1,399₹1,399",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 7,
      title:
        "Art Street A4 Size Photo Frame For Wall Set of 5 Black Picture Frame For Home and Office Decoration with Free Hanging Accessories-Size -8x12 Inches",
      asin: "B082PP6MS1",
      link: "https://www.amazon.in/Art-Street-Individual-Hanging-Accessories/dp/B082PP6MS1/ref=sr_1_7?keywords=photo+frames&qid=1638120555&sr=8-7",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61tV8ERdS3L._AC_UL320_.jpg",
      is_prime: true,
      rating: 4,
      ratings_total: 1438,
      prices: [
        {
          symbol: "₹",
          value: 749,
          currency: "INR",
          raw: "₹749",
          name: "₹749₹749 ₹2,499₹2,499",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 2499,
          currency: "INR",
          raw: "₹2,499",
          name: "₹749₹749 ₹2,499₹2,499",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 749,
        currency: "INR",
        raw: "₹749",
        name: "₹749₹749 ₹2,499₹2,499",
        is_primary: true,
      },
    },
    {
      position: 8,
      title: "Amazon Brand - Solimo Collage Photo Frames, Set of 8, Black",
      asin: "B07VYXGYGZ",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Collage-Frames/dp/B07VYXGYGZ/ref=sxin_12_trfob_0_B07VYXGYGZ?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B07VYXGYGZ&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-1-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/910MQefmd0L._AC_UL320_.jpg",
      is_prime: true,
      rating: 4,
      ratings_total: 89,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 799,
          currency: "INR",
          raw: "₹799",
          name: "₹799₹799 ₹1,300₹1,300",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1300,
          currency: "INR",
          raw: "₹1,300",
          name: "₹799₹799 ₹1,300₹1,300",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 799,
        currency: "INR",
        raw: "₹799",
        name: "₹799₹799 ₹1,300₹1,300",
        is_primary: true,
      },
    },
    {
      position: 9,
      title:
        'Amazon Brand - Solimo Set of 14 Photo Frames (4"X6"-14pcs), Brown',
      asin: "B08GD2TTYN",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Frames-14pcs/dp/B08GD2TTYN/ref=sxin_12_trfob_1_B08GD2TTYN?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B08GD2TTYN&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-2-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71xFtjaF34L._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.7,
      ratings_total: 6,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 1099,
          currency: "INR",
          raw: "₹1,099",
          name: "₹1,099₹1,099 ₹1,540₹1,540",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1540,
          currency: "INR",
          raw: "₹1,540",
          name: "₹1,099₹1,099 ₹1,540₹1,540",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1099,
        currency: "INR",
        raw: "₹1,099",
        name: "₹1,099₹1,099 ₹1,540₹1,540",
        is_primary: true,
      },
    },
    {
      position: 10,
      title:
        "Amazon Brand - Solimo Photo Frames, Tabletop (1 pc - 8x12 inch), Black & Silver",
      asin: "B07MHNYF46",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Frames-Tabletop/dp/B07MHNYF46/ref=sxin_12_trfob_2_B07MHNYF46?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B07MHNYF46&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&smid=AT95IG9ONZD7S&sr=1-3-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71o2Lgxu9-L._AC_UL320_.jpg",
      deal: {
        link: "https://www.amazon.in/gp/goldbox/",
        badge_text: "Deal of the Day",
      },
      rating: 4.1,
      ratings_total: 308,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 279,
          currency: "INR",
          raw: "₹279",
          name: "Deal of the Day",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 550,
          currency: "INR",
          raw: "₹550",
          name: "Deal of the Day",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 279,
        currency: "INR",
        raw: "₹279",
        name: "Deal of the Day",
        is_primary: true,
      },
    },
    {
      position: 11,
      title: 'Amazon Brand - Solimo Set of 6 Photo Frames (5"x7"-6pcs) Black',
      asin: "B08GCYXDCH",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Photo-Frames/dp/B08GCYXDCH/ref=sxin_12_trfob_4_B08GCYXDCH?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B08GCYXDCH&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-4-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61f+NySX7ML._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.7,
      ratings_total: 5,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 649,
          currency: "INR",
          raw: "₹649",
          name: "₹649₹649 ₹910₹910",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 910,
          currency: "INR",
          raw: "₹910",
          name: "₹649₹649 ₹910₹910",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 649,
        currency: "INR",
        raw: "₹649",
        name: "₹649₹649 ₹910₹910",
        is_primary: true,
      },
    },
    {
      position: 12,
      title:
        "Amazon Brand - Solimo Set of 5 Black & White Photo Frames With Mount Paper (6 X 8 Inch - 3 Pcs Black & 2 Pc White)",
      asin: "B08GD2K3Y7",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Black-Frames/dp/B08GD2K3Y7/ref=sxin_12_trfob_5_B08GD2K3Y7?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B08GD2K3Y7&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-5-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71iK2dBVxkL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.7,
      ratings_total: 9,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 549,
          currency: "INR",
          raw: "₹549",
          name: "₹549₹549 ₹770₹770",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 770,
          currency: "INR",
          raw: "₹770",
          name: "₹549₹549 ₹770₹770",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 549,
        currency: "INR",
        raw: "₹549",
        name: "₹549₹549 ₹770₹770",
        is_primary: true,
      },
    },
    {
      position: 13,
      title: 'Amazon Brand - Solimo Set of 7 Photo Frames (8"X10": 7pcs) Brown',
      asin: "B08GD3WN1C",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Photo-Frames/dp/B08GD3WN1C/ref=sxin_12_trfob_6_B08GD3WN1C?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B08GD3WN1C&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-6-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/719yxMVfRqL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.2,
      ratings_total: 4,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 949,
          currency: "INR",
          raw: "₹949",
          name: "₹949₹949 ₹1,400₹1,400",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1400,
          currency: "INR",
          raw: "₹1,400",
          name: "₹949₹949 ₹1,400₹1,400",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 949,
        currency: "INR",
        raw: "₹949",
        name: "₹949₹949 ₹1,400₹1,400",
        is_primary: true,
      },
    },
    {
      position: 14,
      title:
        'Amazon Brand - Solimo Synthetic Black Photo Frames Set of 10 with Two plaque " Family" & "Love"',
      asin: "B08GD2Q8BL",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Synthetic-Frames/dp/B08GD2Q8BL/ref=sxin_12_trfob_7_B08GD2Q8BL?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B08GD2Q8BL&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-7-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71XftALNAuL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.4,
      ratings_total: 9,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 1044,
          currency: "INR",
          raw: "₹1,044",
          name: "₹1,044₹1,044 ₹1,540₹1,540",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1540,
          currency: "INR",
          raw: "₹1,540",
          name: "₹1,044₹1,044 ₹1,540₹1,540",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1044,
        currency: "INR",
        raw: "₹1,044",
        name: "₹1,044₹1,044 ₹1,540₹1,540",
        is_primary: true,
      },
    },
    {
      position: 15,
      title:
        'Amazon Brand - Solimo Black Photo Frames Set of 12 ( 5 X 7 inch - 8 Pcs & 8 x 10 inch - 4 pcs) with Two plaque " Family" & "Love"',
      asin: "B08GCWWJXS",
      link: "https://www.amazon.in/Amazon-Brand-Solimo-Frames-plaque/dp/B08GCWWJXS/ref=sxin_12_trfob_8_B08GCWWJXS?cv_ct_cx=photo+frames&keywords=photo+frames&pd_rd_i=B08GCWWJXS&pd_rd_r=41e48092-d5ac-4bc5-a025-3ad9f5d9f18c&pd_rd_w=ooIY3&pd_rd_wg=OL81a&pf_rd_p=2f622495-a6aa-4184-9723-83b7461bae6a&pf_rd_r=DMJ3RQDH0ZSEB99NWJD3&qid=1638120555&sr=1-8-6628e1d3-2713-4d39-a17a-6cfde7413f03",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71iDLhJyhEL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.9,
      ratings_total: 5,
      is_carousel: true,
      carousel: {
        title: "Top rated: Made for Amazon",
        sub_title: "Amazon’s private and select curated brands",
        id: "loom-desktop-inline-slot_eu-slds-pb-trfob-fa",
        total_items: 8,
      },
      prices: [
        {
          symbol: "₹",
          value: 1149,
          currency: "INR",
          raw: "₹1,149",
          name: "₹1,149₹1,149 ₹1,610₹1,610",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1610,
          currency: "INR",
          raw: "₹1,610",
          name: "₹1,149₹1,149 ₹1,610₹1,610",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1149,
        currency: "INR",
        raw: "₹1,149",
        name: "₹1,149₹1,149 ₹1,610₹1,610",
        is_primary: true,
      },
    },
    {
      position: 16,
      title:
        'Art Street Synthetic Table/Wall Photo Frame for Home Decor (4" X 6", Black)',
      asin: "B01LLPOJTA",
      link: "https://www.amazon.in/Painting-Mantra-Synthetic-Table-inches/dp/B01LLPOJTA/ref=sr_1_8?keywords=photo+frames&qid=1638120555&sr=8-8",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/619N7BbdrSL._AC_UL320_.jpg",
      rating: 3.8,
      ratings_total: 687,
      prices: [
        {
          symbol: "₹",
          value: 129,
          currency: "INR",
          raw: "₹129",
          name: "₹129₹129 ₹250₹250",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 250,
          currency: "INR",
          raw: "₹250",
          name: "₹129₹129 ₹250₹250",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 129,
        currency: "INR",
        raw: "₹129",
        name: "₹129₹129 ₹250₹250",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 17,
      title:
        "Art Street -Photo Frame Set Black Chief 6 Pcs (Photo Size 8x10 Inches - 2 Units, 6x8 inches 4 Units. (Free Hanging Accessories and Papper Mount)",
      asin: "B07GCL2XGS",
      link: "https://www.amazon.in/Art-Street-Individual-Frames-Hanging/dp/B07GCL2XGS/ref=sr_1_9?keywords=photo+frames&qid=1638120555&sr=8-9",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61ElkO+qutL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.1,
      ratings_total: 574,
      prices: [
        {
          symbol: "₹",
          value: 699,
          currency: "INR",
          raw: "₹699",
          name: "₹699₹699 ₹2,000₹2,000",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 2000,
          currency: "INR",
          raw: "₹2,000",
          name: "₹699₹699 ₹2,000₹2,000",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 699,
        currency: "INR",
        raw: "₹699",
        name: "₹699₹699 ₹2,000₹2,000",
        is_primary: true,
      },
    },
    {
      position: 18,
      title:
        'AG Crafts™ Classic Frame with Mount Set of 12 Individual Photo Frames (6"x8"-12 Set with Mount) (Black with Mount)',
      asin: "B08KGHZHY1",
      link: "https://www.amazon.in/AG-CraftsTM-Classic-Individual-Frames/dp/B08KGHZHY1/ref=sr_1_10?keywords=photo+frames&qid=1638120555&sr=8-10",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71391BIdyuL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.2,
      ratings_total: 374,
      prices: [
        {
          symbol: "₹",
          value: 699,
          currency: "INR",
          raw: "₹699",
          name: "₹699₹699 ₹1,199₹1,199",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1199,
          currency: "INR",
          raw: "₹1,199",
          name: "₹699₹699 ₹1,199₹1,199",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 699,
        currency: "INR",
        raw: "₹699",
        name: "₹699₹699 ₹1,199₹1,199",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Thursday, December 2",
      },
    },
    {
      position: 19,
      title:
        "AG Crafts™ Collage Photo Frames, Set of 7,Wall Hanging (6 pcs - 4x6 inch, 1 pcs - 5x7 inch) (Black)",
      asin: "B08GH43XB9",
      link: "https://www.amazon.in/AG-CraftsTM-Collage-Frames-Hanging/dp/B08GH43XB9/ref=sr_1_11?keywords=photo+frames&qid=1638120555&sr=8-11",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61BFUSg2MHL._AC_UL320_.jpg",
      rating: 3.9,
      ratings_total: 838,
      prices: [
        {
          symbol: "₹",
          value: 389,
          currency: "INR",
          raw: "₹389",
          name: "₹389₹389 ₹799₹799",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 799,
          currency: "INR",
          raw: "₹799",
          name: "₹389₹389 ₹799₹799",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 389,
        currency: "INR",
        raw: "₹389",
        name: "₹389₹389 ₹799₹799",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 20,
      title:
        "Art Street Wall Photo Frame Sumptuous Vibrant Photo Frame Collage for Home Decoration (White, Green, Pink - Set of 15)",
      asin: "B08BXJXK9R",
      link: "https://www.amazon.in/Art-Street-Synthetic-Hanging-Accessories/dp/B08BXJXK9R/ref=sr_1_12?keywords=photo+frames&qid=1638120555&sr=8-12",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71QXFY06YwL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4,
      ratings_total: 644,
      prices: [
        {
          symbol: "₹",
          value: 1499,
          currency: "INR",
          raw: "₹1,499",
          name: "₹1,499₹1,499 ₹3,000₹3,000",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 3000,
          currency: "INR",
          raw: "₹3,000",
          name: "₹1,499₹1,499 ₹3,000₹3,000",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 1499,
        currency: "INR",
        raw: "₹1,499",
        name: "₹1,499₹1,499 ₹3,000₹3,000",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 21,
      title: "AG Crafts� Wall 11 Collage Photo Frames Black (Black)",
      asin: "B08KW2655F",
      link: "https://www.amazon.in/AG-CraftsTM-Collage-Photo-Frames/dp/B08KW2655F/ref=sr_1_13?keywords=photo+frames&qid=1638120555&sr=8-13",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61VVFflRxnL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.9,
      ratings_total: 204,
      prices: [
        {
          symbol: "₹",
          value: 579,
          currency: "INR",
          raw: "₹579",
          name: "₹579₹579 ₹1,199₹1,199",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1199,
          currency: "INR",
          raw: "₹1,199",
          name: "₹579₹579 ₹1,199₹1,199",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 579,
        currency: "INR",
        raw: "₹579",
        name: "₹579₹579 ₹1,199₹1,199",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 22,
      title:
        "PERSONALIZED WORLD Customize mosaic photo frame with mosaic photo (50 photos)",
      asin: "B07KN5TJVG",
      link: "https://www.amazon.in/Personalized-World-Customized-Photo-Frame/dp/B07KN5TJVG/ref=sr_1_14?keywords=photo+frames&qid=1638120555&sr=8-14",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/81iN0LWVTEL._AC_UL320_.jpg",
      rating: 4,
      ratings_total: 202,
      prices: [
        {
          symbol: "₹",
          value: 495,
          currency: "INR",
          raw: "₹495",
          name: "₹495₹495 ₹1,585₹1,585",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1585,
          currency: "INR",
          raw: "₹1,585",
          name: "₹495₹495 ₹1,585₹1,585",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 495,
        currency: "INR",
        raw: "₹495",
        name: "₹495₹495 ₹1,585₹1,585",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 23,
      title:
        'AJANTA ROYAL Personalized Collage Photo Frames for Walls Decoration (10" x 15" Inch, Metallic)',
      asin: "B082542YNB",
      link: "https://www.amazon.in/AJANTA-ROYAL-Personalized-Decoration-Metallic/dp/B082542YNB/ref=sr_1_15?keywords=photo+frames&qid=1638120555&sr=8-15",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/91O9Wg7Qz1L._AC_UL320_.jpg",
      prices: [
        {
          symbol: "₹",
          value: 499,
          currency: "INR",
          raw: "₹499",
          name: "Primary",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 799,
          currency: "INR",
          raw: "₹799",
          name: "Original",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 499,
        currency: "INR",
        raw: "₹499",
        name: "Primary",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Friday, December 3",
      },
    },
    {
      position: 24,
      title: "Painting Mantra White Flower Table Photo Frame - 4X6",
      asin: "B01L7FF858",
      link: "https://www.amazon.in/Painting-Mantra-White-Flower-Table/dp/B01L7FF858/ref=sr_1_16?keywords=photo+frames&qid=1638120555&sr=8-16",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61Z1RkuCg-S._AC_UL320_.jpg",
      rating: 4.2,
      ratings_total: 952,
      prices: [
        {
          symbol: "₹",
          value: 247,
          currency: "INR",
          raw: "₹247",
          name: "₹247₹247 ₹500₹500",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 500,
          currency: "INR",
          raw: "₹500",
          name: "₹247₹247 ₹500₹500",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 247,
        currency: "INR",
        raw: "₹247",
        name: "₹247₹247 ₹500₹500",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 25,
      title: "AG Crafts Wood Wall Photo Frame (Black, 12 Photos)",
      asin: "B08KW6FK4W",
      link: "https://www.amazon.in/AG-Crafts-Photo-Frame-Photos/dp/B08KW6FK4W/ref=sr_1_17?keywords=photo+frames&qid=1638120555&sr=8-17",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61r2kILHbxL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4,
      ratings_total: 404,
      prices: [
        {
          symbol: "₹",
          value: 589,
          currency: "INR",
          raw: "₹589",
          name: "₹589₹589 ₹1,499₹1,499",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1499,
          currency: "INR",
          raw: "₹1,499",
          name: "₹589₹589 ₹1,499₹1,499",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 589,
        currency: "INR",
        raw: "₹589",
        name: "₹589₹589 ₹1,499₹1,499",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 26,
      title:
        "ArtzFolio Wall Photo Frame D237 Black Set of 2 Units with Mount | with Back Stand | 8x10inch",
      asin: "B07MDFS4VQ",
      link: "https://www.amazon.in/Artzfolio-Photo-Frame-Black-8X10Inch/dp/B07MDFS4VQ/ref=sr_1_18?keywords=photo+frames&qid=1638120555&sr=8-18",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71qofVnF+pL._AC_UL320_.jpg",
      rating: 3.4,
      ratings_total: 77,
      prices: [
        {
          symbol: "₹",
          value: 329,
          currency: "INR",
          raw: "₹329",
          name: "₹329₹329 ₹939₹939",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 939,
          currency: "INR",
          raw: "₹939",
          name: "₹329₹329 ₹939₹939",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 329,
        currency: "INR",
        raw: "₹329",
        name: "₹329₹329 ₹939₹939",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Tuesday, November 30",
      },
    },
    {
      position: 27,
      title:
        "PAPER PLANE DESIGN Family Tree Collage Photo Frames for Wall Decor Set (Style-7)",
      asin: "B08TT7W9QY",
      link: "https://www.amazon.in/PAPER-PLANE-DESIGN-Collage-Style-7/dp/B08TT7W9QY/ref=sr_1_19?keywords=photo+frames&qid=1638120555&sr=8-19",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/81QBCpUVSIL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.8,
      ratings_total: 153,
      prices: [
        {
          symbol: "₹",
          value: 649,
          currency: "INR",
          raw: "₹649",
          name: "₹649₹649 ₹2,299₹2,299",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 2299,
          currency: "INR",
          raw: "₹2,299",
          name: "₹649₹649 ₹2,299₹2,299",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 649,
        currency: "INR",
        raw: "₹649",
        name: "₹649₹649 ₹2,299₹2,299",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Saturday, December 4",
      },
    },
    {
      position: 28,
      title:
        "DJ ARTS Family Photo Frame Set Of 7 Picture Frames Family MDF Plaque |6 Units 4x6, 1 Units 5x7|",
      asin: "B09J19GQ1N",
      link: "https://www.amazon.in/DJ-ARTS-Family-Picture-Frames/dp/B09J19GQ1N/ref=sr_1_20?keywords=photo+frames&qid=1638120555&sr=8-20",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71RC47BUWZL._AC_UL320_.jpg",
      rating: 4.4,
      ratings_total: 3,
      prices: [
        {
          symbol: "₹",
          value: 329,
          currency: "INR",
          raw: "₹329",
          name: "₹329₹329 ₹999₹999",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 999,
          currency: "INR",
          raw: "₹999",
          name: "₹329₹329 ₹999₹999",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 329,
        currency: "INR",
        raw: "₹329",
        name: "₹329₹329 ₹999₹999",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Friday, December 3",
      },
    },
    {
      position: 29,
      title:
        "Amazon Brand - Solimo Photo Frames, Tabletop (1 pc - 8x12 inch), Rosewood Color",
      asin: "B07LH5WWFS",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_mtf_aps_sr_pg1_1?ie=UTF8&adId=A0952530374AZS066QU2J&url=%2FAmazon-Brand-Solimo-Tabletop-Rosewood%2Fdp%2FB07LH5WWFS%2Fref%3Dsr_1_21_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26smid%3DAT95IG9ONZD7S%26sr%3D8-21-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_mtf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71C4tM+6xYL._AC_UL320_.jpg",
      deal: {
        link: "https://www.amazon.in/gp/goldbox/",
        badge_text: "Deal of the Day",
      },
      rating: 4.1,
      ratings_total: 308,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 279,
          currency: "INR",
          raw: "₹279",
          name: "Deal of the Day",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 550,
          currency: "INR",
          raw: "₹550",
          name: "Deal of the Day",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 279,
        currency: "INR",
        raw: "₹279",
        name: "Deal of the Day",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 30,
      title:
        "Amazon Brand - Solimo Collage Photo Frames, Set of 3, Tabletop (2 pcs - 4x6 inch, 1 pc - 6x8 inch), Golden",
      asin: "B07LH5Y15K",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_mtf_aps_sr_pg1_1?ie=UTF8&adId=A0951974162BE6Z711A8&url=%2FAmazon-Brand-Solimo-Collage-Tabletop%2Fdp%2FB07LH5Y15K%2Fref%3Dsr_1_22_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26smid%3DAT95IG9ONZD7S%26sr%3D8-22-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_mtf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/81FTwa+pvfL._AC_UL320_.jpg",
      deal: {
        link: "https://www.amazon.in/gp/goldbox/",
        badge_text: "Deal of the Day",
      },
      rating: 4.1,
      ratings_total: 377,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 379,
          currency: "INR",
          raw: "₹379",
          name: "Deal of the Day",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 750,
          currency: "INR",
          raw: "₹750",
          name: "Deal of the Day",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 379,
        currency: "INR",
        raw: "₹379",
        name: "Deal of the Day",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 31,
      title:
        "Amazon Brand - Solimo Collage Photo Frames, Set of 3, Tabletop (3 pcs - 5x7 inch), Rosewood Color",
      asin: "B07LH3RFFC",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_mtf_aps_sr_pg1_1?ie=UTF8&adId=A09513943KT63JUO7633G&url=%2FAmazon-Brand-Collage-Tabletop-Rosewood%2Fdp%2FB07LH3RFFC%2Fref%3Dsr_1_23_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26sr%3D8-23-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_mtf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71XfM0++-uL._AC_UL320_.jpg",
      rating: 4.2,
      ratings_total: 248,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 399,
          currency: "INR",
          raw: "₹399",
          name: "₹399₹399 ₹800₹800",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 800,
          currency: "INR",
          raw: "₹800",
          name: "₹399₹399 ₹800₹800",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 399,
        currency: "INR",
        raw: "₹399",
        name: "₹399₹399 ₹800₹800",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 32,
      title:
        "VAH Black Wooden Photo Frame - Display Picture Collage Organizer with Clips (My Journey)",
      asin: "B0926C8FPM",
      link: "https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_mtf_aps_sr_pg1_1?ie=UTF8&adId=A07833391WEIL71OFRB9J&url=%2FVAH-Black-Wooden-Photo-Frame%2Fdp%2FB0926C8FPM%2Fref%3Dsr_1_24_sspa%3Fkeywords%3Dphoto%2Bframes%26qid%3D1638120555%26sr%3D8-24-spons%26psc%3D1&qualifier=1638120555&id=1733179436288020&widgetName=sp_mtf",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61dVJ-BzUiL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.2,
      ratings_total: 615,
      sponsored: true,
      prices: [
        {
          symbol: "₹",
          value: 499,
          currency: "INR",
          raw: "₹499",
          name: "₹499₹499 ₹1,999₹1,999",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1999,
          currency: "INR",
          raw: "₹1,999",
          name: "₹499₹499 ₹1,999₹1,999",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 499,
        currency: "INR",
        raw: "₹499",
        name: "₹499₹499 ₹1,999₹1,999",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Wednesday, December 1",
      },
    },
    {
      position: 33,
      title:
        "Art Street Photo Frame For Wall Set of 3 Brown Picture Frame For Home and Office Decoration with Free Hanging Accessories-Size -6.7x30, 5x5 Inches",
      asin: "B09434D6RF",
      link: "https://www.amazon.in/Art-Street-Picture-Decoration-Accessories-Size/dp/B09434D6RF/ref=sr_1_25?keywords=photo+frames&qid=1638120555&sr=8-25",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/51tHC8bbv2L._AC_UL320_.jpg",
      rating: 3.7,
      ratings_total: 11,
      prices: [
        {
          symbol: "₹",
          value: 299,
          currency: "INR",
          raw: "₹299",
          name: "₹299₹299 ₹999₹999",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 999,
          currency: "INR",
          raw: "₹999",
          name: "₹299₹299 ₹999₹999",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 299,
        currency: "INR",
        raw: "₹299",
        name: "₹299₹299 ₹999₹999",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Saturday, December 4",
      },
    },
    {
      position: 34,
      title:
        "Aayog Creations Hanging Photo Frame Collage with Your Photo with Wooden Clips A Unique Gift for Birthday Anniversary Moments",
      asin: "B09M54V88Z",
      link: "https://www.amazon.in/Aayog-Creations-Hanging-Birthday-Anniversary/dp/B09M54V88Z/ref=sr_1_26?keywords=photo+frames&qid=1638120555&sr=8-26",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61DvsHxUxLS._AC_UL320_.jpg",
      is_prime: true,
      prices: [
        {
          symbol: "₹",
          value: 299,
          currency: "INR",
          raw: "₹299",
          name: "Primary",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 999,
          currency: "INR",
          raw: "₹999",
          name: "Original",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 299,
        currency: "INR",
        raw: "₹299",
        name: "Primary",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Thursday, December 2",
      },
    },
    {
      position: 35,
      title:
        "Art Street Photo Frame For Wall Set of 10 Black Picture Frames For Home Decoration , Wall Decor EcoSeries -Size -6x8,5x7 Inches",
      asin: "B08XZLKT1T",
      link: "https://www.amazon.in/Art-Street-Picture-Decoration-EcoSeries/dp/B08XZLKT1T/ref=sr_1_27?keywords=photo+frames&qid=1638120555&sr=8-27",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61Q8Qr1LBeL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.8,
      ratings_total: 184,
      prices: [
        {
          symbol: "₹",
          value: 499,
          currency: "INR",
          raw: "₹499",
          name: "₹499₹499 ₹1,500₹1,500",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1500,
          currency: "INR",
          raw: "₹1,500",
          name: "₹499₹499 ₹1,500₹1,500",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 499,
        currency: "INR",
        raw: "₹499",
        name: "₹499₹499 ₹1,500₹1,500",
        is_primary: true,
      },
    },
    {
      position: 36,
      title: "Stuthi Arts Wood MDF Photo Frame With Glass (Black, 11Photos)",
      asin: "B096MSBSVJ",
      link: "https://www.amazon.in/Stuthi-Arts-Photo-Frame-11Photos/dp/B096MSBSVJ/ref=sr_1_28?keywords=photo+frames&qid=1638120555&sr=8-28",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61RFMCkOewL._AC_UL320_.jpg",
      is_prime: true,
      rating: 3.9,
      ratings_total: 93,
      prices: [
        {
          symbol: "₹",
          value: 599,
          currency: "INR",
          raw: "₹599",
          name: "₹599₹599 ₹1,699₹1,699",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 1699,
          currency: "INR",
          raw: "₹1,699",
          name: "₹599₹599 ₹1,699₹1,699",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 599,
        currency: "INR",
        raw: "₹599",
        name: "₹599₹599 ₹1,699₹1,699",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Thursday, December 2",
      },
    },
    {
      position: 37,
      title:
        "PRINTZILLA Personalized Customized Magic Mirror Cum Photo Frame with LED Lights for Home Decor, White",
      asin: "B08FV2BXW9",
      link: "https://www.amazon.in/PRINTZILLA-Personalized-Customized-Mirror-Plastic/dp/B08FV2BXW9/ref=sr_1_29?keywords=photo+frames&qid=1638120555&sr=8-29",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/81B6WCdQJeS._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.3,
      ratings_total: 250,
      prices: [
        {
          symbol: "₹",
          value: 498,
          currency: "INR",
          raw: "₹498",
          name: "₹498₹498 ₹799₹799",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 799,
          currency: "INR",
          raw: "₹799",
          name: "₹498₹498 ₹799₹799",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 498,
        currency: "INR",
        raw: "₹498",
        name: "₹498₹498 ₹799₹799",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Thursday, December 2",
      },
    },
    {
      position: 38,
      title:
        "DJ ARTS Photo Frame Set of 7 Picture Wall Hanging Accessiores (Black 4x6-6 5x7-1 Frame)",
      asin: "B09J16JKPZ",
      link: "https://www.amazon.in/DJ-ARTS-Picture-Hanging-Accessiores/dp/B09J16JKPZ/ref=sr_1_30?keywords=photo+frames&qid=1638120555&sr=8-30",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/71HNmF6-gYL._AC_UL320_.jpg",
      rating: 3.3,
      ratings_total: 3,
      prices: [
        {
          symbol: "₹",
          value: 318,
          currency: "INR",
          raw: "₹318",
          name: "₹318₹318 ₹999₹999",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 999,
          currency: "INR",
          raw: "₹999",
          name: "₹318₹318 ₹999₹999",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 318,
        currency: "INR",
        raw: "₹318",
        name: "₹318₹318 ₹999₹999",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Friday, December 3",
      },
    },
    {
      position: 39,
      title:
        'Art India Collections Decorative Table Photo Frame 4x6", Diwali Gifting Photo Frame, Brass and Glass Standing Frame',
      asin: "B08DLQLFXN",
      link: "https://www.amazon.in/Collections-Decorative-Diwali-Gifting-Standing/dp/B08DLQLFXN/ref=sr_1_31?keywords=photo+frames&qid=1638120555&sr=8-31",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/61x4UI43h8L._AC_UL320_.jpg",
      rating: 3.8,
      ratings_total: 23,
      prices: [
        {
          symbol: "₹",
          value: 489,
          currency: "INR",
          raw: "₹489",
          name: "₹489₹489 ₹850₹850",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 850,
          currency: "INR",
          raw: "₹850",
          name: "₹489₹489 ₹850₹850",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 489,
        currency: "INR",
        raw: "₹489",
        name: "₹489₹489 ₹850₹850",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Saturday, December 4",
      },
    },
    {
      position: 40,
      title:
        "Giftplease Acrylic Customized Photo and song Glass Spotify Plaque with wooden stand | Personalized Photo Music Frame with scannable code (Transparent, Clear , 6 x 9 Inches)",
      asin: "B08XXJ1P35",
      link: "https://www.amazon.in/Giftplease-Customized-Personalized-scannable-Transparent/dp/B08XXJ1P35/ref=sr_1_32?keywords=photo+frames&qid=1638120555&sr=8-32",
      categories: [
        {
          name: "All Categories",
          id: "aps",
        },
      ],
      image: "https://m.media-amazon.com/images/I/81Y-9RpHUTL._AC_UL320_.jpg",
      is_prime: true,
      rating: 4.2,
      ratings_total: 313,
      prices: [
        {
          symbol: "₹",
          value: 499,
          currency: "INR",
          raw: "₹499",
          name: "₹499₹499 ₹2,499₹2,499",
          is_primary: true,
        },
        {
          symbol: "₹",
          value: 2499,
          currency: "INR",
          raw: "₹2,499",
          name: "₹499₹499 ₹2,499₹2,499",
          is_rrp: true,
        },
      ],
      price: {
        symbol: "₹",
        value: 499,
        currency: "INR",
        raw: "₹499",
        name: "₹499₹499 ₹2,499₹2,499",
        is_primary: true,
      },
      delivery: {
        tagline: "Get it by Saturday, December 4",
      },
    },
  ],
};

export default data1;
